//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp13.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Department { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Reason Reason1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
